### PR TITLE
When an error happens during a usb transfer, don't emit an error.

### PR DESCRIPTION
**Pull request by zvin**
Remove the device instead.

Change-Type: patch

### CODE REVIEW

**Comment by jhermsmeier** [comment]
Why is this change necessary? And why would we want to ignore errors in the second stage, without communicating the failure?

**Comment by zvin** [comment]
>Why is this change necessary? And why would we want to ignore errors in the second stage, without communicating the failure?

@jhermsmeier this error will happen if you unplug the rpi zero during the 2nd stage.
We only want to signal that this device is detached. Emitting an error on the adapter is useless because:
 * we don't know on which device the error occurred
 * we don't care (we only want to know that the device is no longer available) -> `detach` event instead of `error`
 * currently etcher will stop the device scanner if any error occurs, this is not a fatal error, other devices will get discovered if plugged in.

**Comment by jhermsmeier** [comment]
> currently etcher will stop the device scanner if any error occurs,

well, we should definitely fix that, and maybe just fix that instead of swallowing errors here, I think

**Comment by zvin** [comment]
@jhermsmeier we expect that devices might be unplugged.
We're not swallowing the error here, we expect it and we react in consequence: we emit a 'detach' event.

**Comment by curcuz** [comment]
a detach event is def. not an error imo, approved

**Pull request merged**
